apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name | quote }}
        {{- end }}
      containers:
        - name: {{ .Values.fullnameOverride }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- else if .value }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
        #   livenessProbe:
        #     httpGet:
        #       path: {{ .Values.livenessProbe.httpGet.path }}
        #       port: {{ .Values.livenessProbe.httpGet.port }}
        #   readinessProbe:
        #     httpGet:
        #       path: {{ .Values.readinessProbe.httpGet.path }}
        #       port: {{ .Values.readinessProbe.httpGet.port }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      
