apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride }}
spec:
  selector:
    app: {{ .Values.fullnameOverride }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: ClusterIP
