apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
imagePullSecrets:
  {{- range .Values.imagePullSecrets }}
  - name: {{ .name | quote }}
  {{- end }}
